# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:

  # Various general + format-specific helpers
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: check-symlinks
    - id: trailing-whitespace
    - id: mixed-line-ending
      args: [--fix=lf]
    - id: check-yaml
      exclude: 'mkdocs.yml'
    - id: check-toml
    - id: check-json
    - id: check-ast
    - id: debug-statements
    - id: check-merge-conflict
    - id: check-shebang-scripts-are-executable
    - id: check-added-large-files
      args: [--maxkb=10000]
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: '0.22.0'
    hooks:
    - id: check-github-workflows

  # Quality
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.1.1'
    hooks:
      - id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]
        # NOTE: you might need to add some deps here:
        additional_dependencies: []

  # Metadata
  - repo: https://github.com/citation-file-format/cff-converter-python
    rev: '44e8fc9'
    hooks:
      - id: validate-cff
  - repo: https://github.com/fsfe/reuse-tool
    rev: 'v1.1.2'
    hooks:
      - id: reuse

  - repo: https://github.com/Materials-Data-Science-and-Informatics/somesy
    rev: 'v0.1.0'
    hooks:
      - id: somesy
